#!/usr/bash

# run all python unittests in a directory
alias pyut_d="python -m unittest discover"
alias gg="go_git"
complete -F _go_git gg
alias lc="lazy_commit"
alias go_grade="echo -e 'Going to grade on the linux host for PSU CS...'; ssh linux -t 'cd grading-folder; bash'" 
alias supg="sudo apt-get update && sudo apt-get upgrade"
